name: build-main-file
on: [push, pull_request]

jobs:
  test-build-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "Mulai build golang binary"
    - uses: actions/setup-go@v5

      with:
        go-version: '1.21.6'
    - run: go build -o bin/main cmd/main.go
